service: comment-api-service
app: comment-api
org: fabiorocha22

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  stage: dev
  # cfnRole: arn:aws:iam::502661971098:role/comment-api-service-dev-IamRoleCustomResourcesLamb-VN0PJ2X2AH1W
  environment:
    MYSQLHOST: 'comment-app-database.cs818ogrqhyw.sa-east-1.rds.amazonaws.com'
    MYSQLPORT: '3306'
    MYSQLUSER: 'fabio'
    MYSQLPASS: 'fabio22051996'
    MYSQLDATABASE: 'comment_db'
    MYSQLDIALECT: 'mysql'

functions:
  getcomment:
    handler: handler.getAllComment
    environment:
      bucket: comment-api
    events:
      - http:
          path: getcomment
          method: get
          cors: true
  appendcomment:
    handler: handler.appendComment
    environment:
      bucket: comment-api
    events:
      - http:
          path: appendcomment
          method: post
          cors: true
  speech:
    handler: handler.speech
    environment:
      bucket: comment-api
    events:
      - http:
          path: speech
          method: post
          cors: true

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

plugins:
  - serverless-offline